<?php

const DEFAULT_CHOICE = 3;

/**
 * Implementation of hook_preprocess_node().
 */
function waziers_module_preprocess_node(&$variables) {
  global $user;

  $variables['waziers_choice'] = _waziers_module_getChoice(intval($variables['nid']), intval($user->uid));

  if (!is_null($variables['waziers_choice'])) {
      $variables['waziers_choice'] = $variables['waziers_choice']->choice;
  }
}

function _waziers_module_getChoice ($nid, $uid) {
  $query = db_select('waziers_choice', 'c');
  $query->fields('c', array('choice', 'nid', 'uid'));
  $query->condition('nid', $nid);
  $query->condition('uid', $uid);

  $result = $query->execute();
  foreach ($result as $record) {
    return $record;
  }

  _waziers_module_insert($nid, $uid, DEFAULT_CHOICE);

  $result = $query->execute();
  foreach ($result as $record) {
    return $record;
  }

  return null;
}


function _waziers_module_insert($nid, $uid, $choiceValue)
{
    $query = db_insert('waziers_choice');
    $query->fields(
      [
        'nid'    => $nid,
        'uid'    => $uid,
        'choice' => $choiceValue,
      ]
    );

    return $query->execute();
}

function _waziers_module_choice_view($nid, $waziersChoice = DEFAULT_CHOICE)
{

    if (module_exists('waziers_module_choose')){
        return  _waziers_module_choose_button($nid, $waziersChoice);
    }

    $variable = variable_get('waziers_choice_' .$waziersChoice);

    $output = '';
    $output .= "<span>{$variable}</span>";

    return $output;
}

function _waziers_module_get_objects()
{

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->propertyCondition('status', NODE_PUBLISHED)
      ->propertyCondition('type', ['objets'])
      ->fieldOrderBy('field_references', 'value', 'ASC');
    $result = $query->execute();

    $newArray = [];
    foreach ($result['node'] as $nid => $node) {
        $newArray [] = node_load($nid);
    }

    return $newArray;
}
